# Site settings
title: Faust Programming Language
email: orlarey@grame.fr
description: > # The official web site of the Faust Programming Language
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://faust.grame.fr" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  orlarey

# Build settings
markdown: kramdown

#exclude: [modules]
incremental: true
